### ISSUE TITLE
need some code snippets for guiding.

### ISSUE THREAD

**Issue by wulixu** [sgjsakura/aspnet5#1]
I'm working on asp.net 5 for learning. before I want to write a paging tag, I found you have one, That's great. and have some comment just like title descripted.

**Comment by sgjsakura** [comment]
@wulixu HI, thank you for your feedback. Unforetunately, the complete demo project is not available yet, but I've write a simple step-by-step guide for you. Please visit the [demo](https://github.com/sgjsakura/aspnet5/blob/master/PagerDemo.md) page. If you have any question, please feel free to reply this issue.

**Comment by zaheedk** [comment]
Hi,

Can you guide on where is the best place to implement pager options. I am able to limit the number of items in my view but without the pageroptions I don't get the navigation links to move between pages.


Thanks
Zaheed

**Comment by sgjsakura** [comment]
@zaheedk Hi, currently the best way to specify the pager options globally is using setupAction argument in `services.UseBootstrapPagerGenerator`, e.g.
```C#
public void ConfigureServices(ISeviceCollection services)
{
  // other configuration steps for your application
  services.UseBootstrapPagerGenerator(options => {
    options.Items = new PagerItemOptions { /* configurations  */ },
    /* other options settings */
  });
}
```
Then you do not need to set `asp-pager-options` for `<nav>` element in your View.

If you have any question, please feel free to reply this issue.

**Comment by zaheedk** [comment]
Hi Sakura,

Thanks for your reply, I done have as suggested and it is working fine.

I have another question which is directly not related to your extension but
would like to pick your brains if you knew. I am using a ViewComponent
Async method for my search results page. Now when I click on the next page
button it appends the page number in the query string but I don't know how
to access the querystring in the View Component so that I can pass the
value in to the PagedList method.

Do you know how this can be achieved.

Thanks
Zaheed

*Zaheed Kanthawala*
zaheedk@gmail.com
027 5353 037

**Comment by zaheedk** [comment]
Hi Sakura,

Don't worry, I have worked it out that using HttpContext.Request I can
access the QueryString.

Cheers
Zaheed

*Zaheed Kanthawala*
zaheedk@gmail.com
027 5353 037

**Comment by sgjsakura** [comment]
@zaheedk Hi, thank you for your feedback. :-) Please feel free to reply or open issues if you have any new question.

**Comment by wulixu** [comment]
@sgjsakura  thanks!
