### ISSUE TITLE
Ajax support

### ISSUE THREAD

**Issue by musabsudan** [sgjsakura/aspnet5#4]
Hi, 

Thank you for the efforts,
I think it is better if you added ajax support to the pager in pagedlist tag helper, not having that is a big turn off and we need to do a workaround to support ajax.

You can add the data-ajax-*

Thanks

**Comment by musabsudan** [comment]
I was reading your code after I put my comment, I found you already have the base in
aspnet5/Sakura.AspNet.Extensions/src/Sakura.AspNet.Mvc.PagedList/Rendering/PagerRenderingItem.cs
```
/// <summary>
/// Get or set all additional HTML attributes which will be applied to the generated link element.
/// </summary>
public IDictionary<string, string> LinkAttributes { get; set; }
```

if we can set multiple extra attributes to the link item (not the pager item) this will solve the issue. but still couldn't find where you set it. I will keep reading.

Regards

**Comment by sgjsakura** [comment]
@musabsudan HI, Thank you for your comment. Originally I've planned to support custom HTML attributes for the generated pager container and item elements, however during it implementation I found there'is a big problem of designing APIs for both flexiable and easy to use scene. The `LinkAttributes` are correctly not used yet due to this problem. I'm now working on a new version of pager tag helpers with completely new API models which trying to solve the above problem, nevertheless, you are very welcome to conbribute your ideas for enhancing the flexibility of the current pager model.

Thank you again for your kind reply :-)

**Comment by musabsudan** [comment]
Thanks for taking time to add the detailed reply.
Cheers!

**Comment by sgjsakura** [comment]
Closing this issue cause it seems the discussion has ended. Please feel free to reopen it if you have any new question.

**Comment by musabsudan** [comment]
yes it is Okay.
actually now I am using [jquery-pjax](https://github.com/defunkt/jquery-pjax) which will solve the issue nicely.
I can recommend it for everyone, not only for this case. because you cannot add support for ajax in every single library that you use.

Thank you.

**Comment by sgjsakura** [comment]
Thank you for your reply. Nevertheless, AJAX is a common requirement for url navigation, thus I will continue to develop the new version, and your kind comment is always very welcome ~
