### ISSUE TITLE
The Sakura.AspNet.IPagedList Count returns the page size instead of the items count in the list

### ISSUE THREAD

**Issue by musabsudan** [sgjsakura/aspnet5#5]
The Sakura.AspNet.IPagedList Count returns the page size instead of the items count in the list

**Comment by sgjsakura** [comment]
@musabsudan HI, thank you for your reply. Unforenately I cannot get your point, do you mean you want to get the total count of the list (instead of the current page)? In this case you should use the `TotalCount` property. The `Count` property is designed work as an implementaion of `ICollection<T>` interface, since the enumeration for a the paged list is usually focused on its current page, the `Count` property also returns the item count of current page.

If you mean this behaviour is excepted however it has bug and returns the wrong number, could you please give a sample for reproduce?

Best wishes,

**Comment by musabsudan** [comment]
I meant the implementation of `Count` property of `ICollection<T>` it returns the page size instead of the items in the current page. Does it works correctly for you?

    `@model Sakura.AspNet.IPagedList

// here the Model.Count will return the page size
@if (Model.Count > 0)
{
    <nav asp-pager-source="Model" ></nav>
}


`

**Comment by sgjsakura** [comment]
@musabsudan HI, could you please tell m

**Comment by sgjsakura** [comment]
HI, could you please tell me your setting for a paged list (TotalCount, PageSize, and PageIndex), I need this information to reproduce this problem. 

Thank you for your feeback~

**Comment by sgjsakura** [comment]
@musabsudan I've now reproduced this problem, there's a bug that `Count` property returns an error value for the last page. The package has updated. 

Thank you for your feedback and please feel free to reopen it if there's still related problem.

**Comment by musabsudan** [comment]
Super! Thanks
